FROM mysql:5.7

ENV MYSQL_DATABASE crm_digital
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_USER crm_digital_user
ENV MYSQL_PASSWORD crmpasswd

COPY mysql.cnf /etc/mysql/conf.d/
# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/
