version: '2'
services:
  zookeeper:
    image: debezium/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
  connect:
    image: debezium/connect
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - SESSION_TIMEOUT_MS=100_000
  consumer:
    build:
      context: .
      dockerfile: Dockerfile-elixir
    links:
      - kafka
      - zookeeper
      - connect
